### PR TITLE
DO NOT MERGE: SH7604 and SH, all the fixes for the saturn, backported ( testing/unofficial )

### PR DESCRIPTION
**Pull request by asturur**
This PR is made by applying blindly the changes to the components available on both the the s32x and the saturn core, but developed for the saturn.
Doing so we fixed one or two issues ( pitfall and xmen )

Saturn work is done without s32x in mind and so this may break things or fix nothing.
Regardless is easy to try, it provides a build for testing to whoever can do so and everyone is welcome to test this build, but there are no expectations.

### CODE REVIEW

**Comment by asturur** [comment]
[S32X_20230704.zip](https://github.com/MiSTer-devel/S32X_MiSTer/files/11947430/S32X_20230704.zip)

**Comment by asturur** [comment]
I didn't test the build yet, i will proceed with the usual things, but i won't test the full library of games.
If someone wants to have a look.
I wouldn't merge before extensive testing is done

**Comment by asturur** [comment]
- Nothing changes in pinocchio UI
- Doom32 resurrection works ok

... i ll do more testing

**Comment by a-barone** [comment]
> * Nothing changes in pinocchio UI
> * Doom32 resurrection works ok
> 
> ... i ll do more testing

I tested several games last night with this build.
Completed MK II, won the Intercontinental Championship in WWF Wrestlemania: The Arcade Game, won races in VR Deluxe, had several fights in VF, played a few stages of Pitfall: TMA, played Star Wars Arcade, played at least 30 minutes of Space Harrier and about 15 minutes of After Burner Completed and D32XR.
No issues were found. 
I want to check the performance compared to the real hardware and update that ticket.

**Comment by asturur** [comment]
Added the recent mult changes
https://github.com/srg320/SH/commit/357ccd8b6e116e24ddc0ac8d47e9248bec1a0ac5

**Comment by Toryalai1** [comment]
> Added the recent mult changes [srg320/SH@357ccd8](https://github.com/srg320/SH/commit/357ccd8b6e116e24ddc0ac8d47e9248bec1a0ac5)

Can you please share build with latest changes?

**Comment by asturur** [comment]
https://github.com/asturur/S32X_MiSTer/releases/download/unstable-builds/S32X_unstable_20230924_215c75.rbf

**Comment by asturur** [comment]
managed to do one late yesterday exactly to post it here

**Comment by asturur** [comment]
pinocchio trembling UI still there.

**Comment by asturur** [comment]
Added 
https://github.com/srg320/SH/commit/956bdb850a4de08cbd8df1dc8e4fc735a8c22839
and
https://github.com/srg320/SH/commit/e5edb8a6a7dd8766535404c3429af0de6da18114

**Comment by asturur** [comment]
as for who wants to try:
https://github.com/asturur/S32X_MiSTer/releases/download/unstable-builds/S32X_unstable_20231004_109be4.rbf

**Comment by asturur** [comment]
i don't see any meaninful changes in my tests. Pinocchio trembling ui is still there.
The visual artifact is correlated with scrolling changing speed

**Comment by asturur** [comment]
https://github.com/asturur/S32X_MiSTer/releases/download/unstable-builds/S32X_unstable_20231010_10fda8.rbf

rebased on latest fix.

**Comment by mario-64** [comment]
> https://github.com/asturur/S32X_MiSTer/releases/download/unstable-builds/S32X_unstable_20231010_10fda8.rbf
> 
> rebased on latest fix.

Does this include the recent Knuckles Chaotix files by @YLFAndy ?

**Comment by asturur** [comment]
yes

**Comment by birdybro** [comment]
This can probably be closed, there have been further changes to the SH core on the Saturn_MiSTer repo. A new PR could probably be opened after someone tests updating to the latest SH module for regressions.

**Comment by asturur** [comment]
Leave it open if it doesn't bother you, we got a single update to the sh2 few days ago and i was about to update it

**Comment by asturur** [comment]
[S32X_unstable_20240208_003007.zip](https://github.com/MiSTer-devel/S32X_MiSTer/files/14203056/S32X_unstable_20240208_003007.zip)

This is the latest commit but i forgot to add the latest main inside

**Comment by asturur** [comment]
## Current official build
Bugs i can reproduce:
[X] pinocchio flicker ui
[ ] Flickers in spiderman web of fire
 
## build 2024028
- all the changes so far
- doesn't fix anything in pinocchio
- star wars arcade attrac mode locks up after a while ( official is fine )

**Comment by asturur** [comment]
### build 20240217
All the changes up to today.

[S32X_unstable_20240216_2392a3.zip](https://github.com/MiSTer-devel/S32X_MiSTer/files/14317348/S32X_unstable_20240216_2392a3.zip)

**Comment by asturur** [comment]
[S32X_unstable_20240227_10a9dc.rbf.zip](https://github.com/MiSTer-devel/S32X_MiSTer/files/14419567/S32X_unstable_20240227_10a9dc.rbf.zip)

**Comment by asturur** [comment]
[S32X_unstable_20240229_16608d.rbf.zip](https://github.com/MiSTer-devel/S32X_MiSTer/files/14548146/S32X_unstable_20240229_16608d.rbf.zip)

**Comment by asturur** [comment]
[S32X_unstable_20240423_19662c.rbf.zip](https://github.com/MiSTer-devel/S32X_MiSTer/files/15093378/S32X_unstable_20240423_19662c.rbf.zip)

Here is the latest build on the latest main / framework

**Comment by sorgelig** [comment]
If there are no issues, then i suggest to merge this PR

**Comment by asturur** [comment]
The build of febraury 8 Had some issue that disappeared after the following updates.
I didn't test the last commit yet becuase i have been busy.
The test i do is usually letting doom and starwar arcade and virtua racing run for hours, on top of checking if some known defects ( only pinocchio ) have disappeared

**Comment by sorgelig** [comment]
No forcing from my side. Take your time for tests.

**Comment by asturur** [comment]
So this latest combination of commits hangs  star wars arcade after 15 minutes or more. something subtle is wrong, and it started happening in febraury.

Definetely is not mergeable.
There could be some commits that are actual corrections ( like the one to some cpu instructions ) but without a failing case fixed isn't really worth it.

We can keep it open or not for visibility and i can still surface or retest a build if a bug surfaces on the official release or if more commits come out.

**Pull request closed without merging**
